language: php
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache"
env:
  global:
  - secure: qOS5AQyl0t8D7NlWAGcZmdqm7n1jP4Hb1rpgHckPNQHPYgbHTpID5hZ89O/uedi5HbRAMaQFyqvnFEx6dhxwYUWrmXv8cd4Dv+DUzKI2teV+1TY7JwWiDKPwVzH+ZlStk4cKCz0fCfhp1moNEjqP+pPXuTqpyf7tF/dAT/q+/evgVU30h74qOr6SnAnk6pZe4xL6hfbsiXDVBxRi0o9tudIMAWM/1/6LArHjsQUu6Nhx0zvrZvDNJByZRTt3kRqpzi+J/8r/2+lf1KU43WO7wnxDkEIho0c8MQHABuTF1MdFXC2V94ak6weBEooCLA3TcTWDMSPT0tAs2QvRI0V4vDH7SUFdjKe3w/G0j6iHRXYT9JMFrTJFmtQ75IUP6p5F8Vr0a7Vlyw9SQvGxj/RekHYCPYVGFKLT3hs0hiIHyMrwCmZj/iHIhG9NcMT/7p3QS3Y/qV2Fi1+xpjXSMbPJjQxP5Q2UOMrHO+iHb4LoTJtLLhrK6PeML188RNYKRi07wx+VSopnAw3BdpGx4pmATshC3FTj8cKH6+0fKuGiB5ajHv1JxfSJHfkbDuZkbiOWMa2I6QtBFZq3FsHTFh5a5tR9OrHaEGxEKPM8F51DuPsDWEXsSfYsgQKtoyDBmopPsDMTXl66xfEoi/+T14rB/41KyAiT3XiqZqjE778hoBw=
  - secure: uiP6ynrIA8mPyl+L6zdfJQTCQK+KhLVvVYvklKCqlrDV++SrnOlNjT1/17arqFFE9B1nNFciYKVg1Otr9SP/C2bJYLACUrQ/1wuTDbppk5sIWpj6baS3fZRKuMPq3pge27oMJWeoxLbMhG4if/AvD6u61NRm+ieDhgYN9yavGZiGOSQMcjkKkv7ylZ6phBmMvkuzVaUOcAh1nvE8uKQwJ+Fc0YtSk0BX8kPagBVMyFTuIZ8TrCPqZXQUJqpDHQIU/3y9vUa4xBw49zBBrIUx6oxfGBCwgUdnsRPDjjuHmV8BXM7v4ihsjFywnBFausjZzwzDho9KBrJySykSCyk3nVHyfN9EFB5rj0Od8MV1bXmir3MovM9utMJREE2w4KajdEw4WeMvWGTG31Aayxm9mJhkco7QXokWYp1MCBAZHvnA2PldjQk9JnNUb62YLbc+35i8iPMvhBAmN0XvHkkDcQoZbg1mPsb+SKFyfxvJ8SyeixSK4HDK6d8BHSKmXE2osZomVRfe4hYpkSBsetibOjd58Wd5AGnyI84yLWURzkqHXEDakml+5GPFSHxu+FWau8jw1mge5/f8E8T5dDUy8nLTII5LCY8sJ0+nl0A+zWz0xEEFXOmIlA4Km1vecBXUibKDu83oeFftcWY9vBGK7RWdenhwKJrL2+DZptYGYHI=
matrix:
  include:
  - php: 5.6
    env: DEPENDENCIES='low'
  - php: 5.6
  - php: hhvm
  - php: 7.0
  - php: 7.0
    env: DEPENDENCIES='dev'
  allow_failures:
  - env: DEPENDENCIES='dev'
  fast_finish: true
before_install:
- if [ "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then phpenv config-rm xdebug.ini; fi
- composer selfupdate
install:
- export COMPOSER_ROOT_VERSION=dev-master;
- export COMPOSER_NO_INTERACTION=1;
- if [ "$DEPENDENCIES" == 'dev' ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/'composer.json;
  fi;
- if [ "$DEPENDENCIES" != 'low' ]; then composer update --prefer-dist --classmap-authoritative;;
  fi;
- if [ "$DEPENDENCIES" == 'low' ]; then composer update --prefer-lowest --prefer-dist
  --classmap-authoritative;fi;
script:
- bin/phpspec run --format=pretty
